// <-- Generated by Github Copilot -->
export type ContextMenuCommandPayload = {
  command: "delete";
  noteId: string;
};

export interface ElectronAPI {
  showContextMenu: (noteId: string) => void;
  onContextMenuCommand: (
    callback: (payload: ContextMenuCommandPayload) => void,
  ) => () => void;
}

declare global {
  interface Window {
    electronAPI: ElectronAPI;
  }
}

export {};
// </- Generated by Github Copilot -->
