import { memo, useCallback, useEffect, useMemo } from "react";
import { useSetAtom } from "jotai";
import { selectedNoteIdAtom } from "src/jotai/atoms";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faDownload,
  faRotate,
  faSpinner,
} from "@fortawesome/free-solid-svg-icons";
import type { Note } from "@shared/types/note";
import { useSetNote } from "src/hooks/useSetNote";
import { getDateOrTime } from "@shared/utils/datetime";

export const NoteListItem = memo(
  ({
    note,
    selected,
    state,
  }: {
    note: Note;
    selected: boolean;
    state: "synced" | "saved" | "unsaved";
  }) => {
    const { id, title, updatedAt } = note;
    const setSelectedNoteId = useSetAtom(selectedNoteIdAtom);
    const dateOrTime = useMemo(() => getDateOrTime(updatedAt), [updatedAt]); // TODO: 日付変更時の更新
    const setNote = useSetNote();

    const deleteNote = useCallback(() => {
      setNote({ ...note, isDeleted: true });
    }, [note, setNote]);

    // <-- Generated by Github Copilot -->
    useEffect(() => {
      if (!window.electronAPI?.onContextMenuCommand) return;

      const cleanup = window.electronAPI.onContextMenuCommand((payload) => {
        if (payload.command === "delete" && payload.noteId === id) {
          deleteNote();
        }
      });

      return cleanup;
    }, [deleteNote, id]);

    const handleContextMenu = useCallback(
      (event: React.MouseEvent<HTMLDivElement>) => {
        event.preventDefault();
        setSelectedNoteId(id);
        window.electronAPI?.showContextMenu?.(id);
      },
      [id, setSelectedNoteId],
    );
    // </- Generated by Github Copilot -->

    return (
      <li className="px-3">
        <div
          className={
            "px-3 py-1 rounded-md" + (selected ? " bg-zinc-800 shadow-lg" : "")
          }
          onClick={() => setSelectedNoteId(id)}
          onContextMenu={handleContextMenu}
        >
          <div>
            <h2 className={"line-clamp-1" + (selected ? " text-zinc-100" : "")}>
              {!title ? "無題" : title}
            </h2>
          </div>
          <div className="flex items-end justify-between">
            <small>
              {state === "synced" && (
                <FontAwesomeIcon icon={faRotate} size="xs" />
              )}
              {state === "saved" && (
                <FontAwesomeIcon icon={faDownload} size="xs" />
              )}
              {state === "unsaved" && (
                <FontAwesomeIcon icon={faSpinner} size="xs" spinPulse />
              )}
              &nbsp;{dateOrTime}
            </small>
          </div>
        </div>
      </li>
    );
  },
);
