import path from "path";
import { app, BrowserWindow, ipcMain, Menu, shell } from "electron";

// <-- Generated by Github Copilot -->
app.whenReady().then(() => {
  const win = new BrowserWindow({
    title: "Quartz Notes",
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      devTools: true,
    },
  });

  if (process.env.VITE_DEV_SERVER_URL) {
    win.loadURL(process.env.VITE_DEV_SERVER_URL);
  } else {
    win.loadFile("dist/index.html");
  }

  win.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: "deny" };
  });

  win.webContents.on("will-navigate", (event, url) => {
    const currentUrl = new URL(win.webContents.getURL());
    const targetUrl = new URL(url);
    if (targetUrl.origin !== currentUrl.origin) {
      event.preventDefault();
      shell.openExternal(url);
    }
  });
});

ipcMain.on("show-context-menu", (event, noteId: string) => {
  const template = [
    {
      label: "削除する",
      click: () => {
        event.sender.send("context-menu-command", {
          command: "delete",
          noteId,
        });
      },
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  menu.popup({
    window: BrowserWindow.fromWebContents(event.sender) || undefined,
  });
});
// </- Generated by Github Copilot -->
