import { contextBridge, ipcRenderer, IpcRendererEvent } from "electron";

// <-- Generated by Github Copilot -->
export type ContextMenuCommandPayload = {
  command: "delete";
  noteId: string;
};

contextBridge.exposeInMainWorld("electronAPI", {
  showContextMenu: (noteId: string) => {
    ipcRenderer.send("show-context-menu", noteId);
  },
  onContextMenuCommand: (
    callback: (payload: ContextMenuCommandPayload) => void,
  ) => {
    const listener = (
      _event: IpcRendererEvent,
      payload: ContextMenuCommandPayload,
    ) => {
      callback(payload);
    };

    ipcRenderer.on("context-menu-command", listener);

    return () => {
      ipcRenderer.removeListener("context-menu-command", listener);
    };
  },
});
// </- Generated by Github Copilot -->
